version: '3'
services:
    api-service:
        build: ./api
        volumes:
            - ./api:/usr/src/app 
        ports:
            - 8000:8000
    worker:
        build: ./celery
        depends_on:
            - redis
    monitor:
        build: ./celery
        ports:
            - 5555:5555
        entrypoint: flower
        command:  -A tasks --port=5555 --broker=redis://redis:6379/0
        depends_on:
            - redis
    redis:
        image: redis
